### PR TITLE
Add new LIFX products

### PR DESCRIPTION
**Pull request by Djelibeybi**
This PR adds new LIFX devices.

### CODE REVIEW

**Comment by Djelibeybi** [comment]
Note that this PR includes manually fixing the following upstream issue: https://github.com/LIFX/products/issues/30

**Comment by frawau** [comment]
Will test and publish soon, probably Saturday. Thanks for the PR

**Comment by Djelibeybi** [comment]
FYI, I've tested this with the new indoor and outdoor Neon Flex, outdoor String and 1600 lumen A19 bulbs with Home Assistant. I'm still waiting for my outdoor spotlight and path lights to arrive for testing purposes.

**Comment by Djelibeybi** [comment]
> I am sure you did ;) I plan to test the release before publishing it to make sure I did no make any mistake.

Of course. I added my comment because yours made me realise I hadn't mentioned any testing in my initial PR or commit messages.

**Pull request merged**
