### PR TITLE
Fix the default callback to save the infrared brightness value

### PR DESCRIPTION
**Pull request by Djelibeybi**
Signed-off-by: Avi Miller <me@dje.li>

### CODE REVIEW

**Comment by frawau** [comment]
Does this require a release?

**Comment by Djelibeybi** [comment]
It does, but it's not urgent. I have a bunch of things to fix for the corresponding Home Assistant PR too.

**Comment by frawau** [comment]
Sorry, my bad, I misunderstood you needed more changes here.... Was waiting for those

**Comment by Djelibeybi** [comment]
Ah, sorry for the confusion. What I meant was that I had other PRs for Home Assistant in-flight before the one that required this change would be ready.

**Pull request merged**
