### PR TITLE
Adds support for HEV Light Control (LIFX Clean)

### PR DESCRIPTION
**Pull request by micolous**
Reference: https://lan.developer.lifx.com/docs/hev-light-control

I'm mainly interested in using this with Home Assistant, there's some people asking about it over here: https://community.home-assistant.io/t/lifx-clean/309219

I added code for it in the example script:

```
% python examples/lifx-cli.py
Hit "Enter" to start
Use Ctrl-C to quit

Select Bulb:
(REDACTED)

Select Function for (REDACTED):
	[1]	Power (0 or 1)
	[2]	White (Brigthness Temperature)
	[3]	Colour (Hue Saturation Brightness)
	[4]	Info
	[5]	Firmware
	[6]	Wifi
	[7]	Uptime
	[8]	Pulse
	[9]	HEV cycle (duration, or -1 to stop)
	[10]	HEV configuration (indication, duration)

	[0]	Back to bulb selection

Your choice: 9
Getting current HEV state
HEV: duration=7200, remaining=0, last_power=True

HEV result: SUCCESS

## Running a HEV cycle with default duration
Your choice: 9 0
Running HEV cycle for 0 second(s)
HEV: duration=7200, remaining=0, last_power=True

## Running a cycle with a custom duration
Your choice: 9 10
Running HEV cycle for 10 second(s)
HEV: duration=10, remaining=0, last_power=True

## Aborting a running cycle
Your choice: 9 -1
Aborting HEV cycle
HEV: duration=10, remaining=0, last_power=True

## Getting the default HEV configuration
Your choice: 10
Getting current HEV configuration
HEV: indication=True, duration=7200

## Setting the default HEV configuration (no indication)
Your choice: 10 0 7199
Configuring default HEV cycle with no indication for 7199 second(s)
HEV: indication=False, duration=7199

## Setting the default HEV configuration (with indication)
Your choice: 10 1 7200
Configuring default HEV cycle with indication for 7200 second(s)
HEV: indication=True, duration=7200
```

### CODE REVIEW

**Comment by frawau** [comment]
I do not have those devices, so I won't be able to check if it works. Will check that it does not break things

Not sure how this is related to #48

**Comment by Djelibeybi** [comment]
@frawau I've updated the products.py and can confirm the HEV support works and no stack traces when run for bulbs without hev support

**Comment by frawau** [comment]
Thanks for updating the product.py

Unfortunately, when using HEV command I get this

```
Your choice: 10 12 10
Configuring default HEV cycle with indication for 10 second(s)
Select Bulb:
        [1]     Entrance
        [2]     Office  Front
        [3]     Office Back

Your choice: Task exception was never retrieved
future: <Task finished name='Task-60' coro=<Device.try_sending() done, defined at /home/fw/development/AutoBuddy/aiolifx/aiolifx/aiolifx.py:275> exception=AttributeError("'NoneType' object has no attribute 'indication'")>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fw/development/AutoBuddy/aiolifx/aiolifx/aiolifx.py", line 306, in try_sending
    myresult = await aio.wait_for(event.wait(), timeout_secs)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fw/development/AutoBuddy/aiolifx/aiolifx/aiolifx.py", line 313, in try_sending
    callb(self, None)
  File "/home/fw/development/AutoBuddy/aiolifx/aiolifx/__main__.py", line 232, in <lambda>
    f"\nHEV: indication={r.indication}, "
AttributeError: 'NoneType' object has no attribute 'indication'
```
Indeed, your last PR only modded product.py. Did you forget some mods?

**Comment by Djelibeybi** [comment]
Yes, I did. Sorry about that. New PR incoming.

**Comment by micolous** [comment]
Thanks for merging. It looks there's now a PR out for Home Assistant to use this https://github.com/home-assistant/core/pull/73060 🎉 

> Not sure how this is related to #48

That was an observation while I was writing this PR – this change _doesn't_ fix it, but at least it doesn't add any _more_ instances of that bug.

**Pull request merged**
