### PR TITLE
Add LIFX String and LIFX Neon to the products list

### PR DESCRIPTION
**Pull request by Djelibeybi**
Also added a check for `upgrades` because it appears to be missing in some of the JSON entries. And I expanded the `.gitignore` file to the default Python file that GitHub creates for a new repo so it covers all the bases.

### CODE REVIEW

**Review by redding1 — COMMENTED** [review]
Nice!

**Comment by frawau** [comment]
Thanks for the PR.  I was working on something similar.... 

I will:
    - manually integrate your "upgrade" fix for update_products
    - copy over the .gitignore 
    - push my changes.

In my changes I separate products.py into products.py and products_defs.py. Updating the list of products becomes trivial 

When I push the changes,  I will ask you to review and test them please.

**Comment by Djelibeybi** [comment]
Sure, will do.

**Comment by frawau** [comment]
Please

**Comment by Djelibeybi** [comment]
I still need to test this: the PR closed after I rebased.

**Comment by Djelibeybi** [comment]
Ok, I've tested a string and it works fine. I will only be able to test a Neon when mine arrives sometime next week, but I wasn't really worried about of them because they're essentially just a fancy lightstrips. :)

**Comment by frawau** [comment]
Thanks. I will publish... going for 1.0.0

**Pull request closed without merging**
